// User-facing API
export { action, query, assertion } from './core/markers'
export { defineDomain } from './core/domain'
export { implement } from './core/adapter'
export { suite } from './core/suite'
export { defineConfig } from './core/config'
export { unit } from './protocols/unit'
export { withFixture } from './core/protocol'
export { getTestContext, runWithTestContext } from './core/test-context'
export { createOtlpReceiver } from './telemetry/otlp-receiver'
export type { OtlpReceiver } from './telemetry/otlp-receiver'
export type { ActionMarker, QueryMarker, AssertionMarker, TelemetryExpectation, TelemetryDeclaration, TelemetryAttributeValue, AsymmetricMatcher } from './core/types'
export type { MarkerOptions } from './core/markers'
export type { Domain } from './core/domain'
export type { Adapter } from './core/adapter'
export type { Protocol, TestMetadata, TestCompletion, TelemetryCollector, CollectedSpan, SpanLink } from './core/protocol'
export type { RunningTestContext } from './core/test-context'
export type { ProtocolExtensions, Screenshotter } from './core/extensions'
export type { RegistrySnapshot } from './core/registry'
export type { AverConfig, AverConfigInput, CoverageConfig, TeardownFailureMode } from './core/config'
export { getCoverageConfig, getTeardownFailureMode } from './core/config'
export type { VocabularyCoverage } from './core/coverage'
export type { TraceEntry, TraceAttachment, TelemetryMatchResult } from './core/trace'
export { verifyCorrelation } from './core/correlation'
export type { CorrelationResult, CorrelationGroup, CorrelationViolation } from './core/correlation'
export type { ActProxy, QueryProxy, AssertProxy, TestContext, SuiteReturn, PlannedTest, SuiteConfig, NamedContext, NamedTestContext, NamedSuiteReturn } from './core/suite'
export type { Clock, StepCategory, TelemetryVerificationMode, ProxyOptions } from './core/proxy'
