// User-facing API
export { action, query, assertion } from './core/markers'
export { defineDomain } from './core/domain'
export { implement } from './core/adapter'
export { suite } from './core/suite'
export { defineConfig } from './core/config'
export { unit } from './protocols/unit'
export { withFixture } from './core/protocol'
export { getTestContext, runWithTestContext } from './core/test-context'
export type { MarkerOptions } from './core/markers'
export type { Domain } from './core/domain'
export type { Adapter } from './core/adapter'
export type { Protocol, TestMetadata, TestCompletion, TelemetryCollector, CollectedSpan, SpanLink } from './core/protocol'
export type { Screenshotter, ProtocolExtensions } from './core/extensions'
export type { AverConfig, AverConfigInput } from './core/config'
export type { TraceEntry, TraceAttachment, TelemetryMatchResult } from './core/trace'
export type { TestContext, SuiteReturn } from './core/suite'
