export { action, query, assertion } from './core/markers'
export { defineDomain } from './core/domain'
export { implement } from './core/adapter'
export { suite } from './core/suite'
export { defineConfig } from './core/config'
export { getAdapters, registerAdapter, findAdapter, findAdapters, resetRegistry } from './core/registry'
export { unit } from './protocols/unit'
export { getTestContext } from './core/test-context'

export type { ActionMarker, QueryMarker, AssertionMarker } from './core/types'
export type { Domain } from './core/domain'
export type { Adapter } from './core/adapter'
export type { Protocol, TestMetadata, TestCompletion } from './core/protocol'
export type { RunningTestContext } from './core/test-context'
export type { ProtocolExtensions, HtmlRenderer } from './core/extensions'
export type { AverConfig } from './core/config'
export type { TraceEntry, TraceAttachment } from './core/trace'
export type { ActProxy, QueryProxy, AssertProxy, TestContext, SuiteReturn } from './core/suite'
