export { action, query, assertion } from './core/markers'
export { defineDomain } from './core/domain'
export { implement } from './core/adapter'
export { suite } from './core/suite'
export { defineConfig } from './core/config'
export { getAdapters, registerAdapter, findAdapter, findAdapters, resetRegistry } from './core/registry'
export { unit } from './protocols/unit'

export type { ActionMarker, QueryMarker, AssertionMarker } from './core/types'
export type { Domain } from './core/domain'
export type { Adapter } from './core/adapter'
export type { Protocol } from './core/protocol'
export type { AverConfig } from './core/config'
export type { TraceEntry, ActProxy, QueryProxy, AssertProxy, TestContext, SuiteReturn } from './core/suite'
