title: Aver
description: Domain-driven acceptance testing for TypeScript
remote_theme: just-the-docs/just-the-docs

color_scheme: aver

plugins:
  - jekyll-remote-theme

url: ""
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock

nav_order_base: 1

aux_links:
  GitHub: https://github.com/averspec/aver

footer_content: "MIT License &copy; 2026 Nate Jackson"
