import { defineDomain, action, query, assertion } from 'aver'

export const averApprovals = defineDomain({
  name: 'AverApprovals',
  actions: {
    approveValue: action<{ value: unknown; name?: string }>(),
    setApproveMode: action(),
    clearApproveMode: action(),
    approveVisual: action<{ name: string; region?: string }>(),
    provideScreenshotter: action<{ behavior: 'match' | 'differ' | 'dimension-mismatch' }>(),
    removeScreenshotter: action(),
  },
  queries: {
    approvedFileExists: query<boolean>(),
    receivedFileContents: query<string>(),
    diffFileContents: query<string>(),
    traceAttachments: query<Array<{ name: string; path: string }>>(),
    lastError: query<string | undefined>(),
    approvedImageExists: query<boolean>(),
    receivedImageExists: query<boolean>(),
    diffImageExists: query<boolean>(),
    lastWarning: query<string | undefined>(),
  },
  assertions: {
    baselineCreated: assertion(),
    baselineMissing: assertion(),
    mismatchDetected: assertion(),
    matchPassed: assertion(),
    diffContains: assertion<{ text: string }>(),
    attachmentsRecorded: assertion<{ minCount: number }>(),
    traceEntryHasStatus: assertion<{ name: string; status: 'pass' | 'fail' }>(),
    noError: assertion(),
    visualBaselineCreated: assertion(),
    visualBaselineMissing: assertion(),
    visualMismatchDetected: assertion(),
    visualMatchPassed: assertion(),
    visualDiffGenerated: assertion(),
    screenshotterSkipWarned: assertion(),
  },
})
