export type { TelemetryEvent, TelemetrySink, InstrumentOptions } from './types.js'
export { instrument } from './instrument.js'
export type { DomainEmitter } from './instrument.js'
export { generateSchema } from './schema.js'
export type { TelemetrySchema } from './schema.js'
export { consoleSink } from './sinks/console.js'
export { structuredLogSink } from './sinks/structured-log.js'
export type { StructuredLogSinkOptions } from './sinks/structured-log.js'
export { scrubPayload } from './scrub.js'
